name: bazora
description: "Bazora - A modern, responsive shopping app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  iconly: ^1.0.1
  flutter_iconly: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.0.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile picture.png
